server:
  port: 8080
spring:
  application:
    name: gilbadak
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gilbadak-local
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
    path: /graphql

jwt:
  secret: 6efca431b36b5d1ad7b70011aa61736ee5f5912d17b750810fc9ac2248ed0d675add3427295172a65b6ce129fe0a610c05eedf6ff5d4e0b52999d27d93fdfc53
  access-token-expiration-time: 1800000 # 30분
  refresh-token-expiration-time: 604800000 # 1주일