services:
  postgres:
    image: postgres
    restart: always
    container_name: gilbadak-db
    volumes:
      - ./gilbadak-local/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: gilbadak-local